bin/nginx.bin: bin/nginx
	x86_64-rumprun-netbsd-cookfs data.fs data
	rumprun-bake -m "add data.fs" hw_generic $@ $<

bin/nginx.hvt: bin/nginx
	rumprun-bake solo5_hvt $@ $<

bin/nginx.spt: bin/nginx
	rumprun-bake solo5_spt $@ $<
